@echo off
echo Reiniciando servidor de desarrollo con optimizaciones...
echo.
echo 🔧 Limpiando cache de Next.js...
rmdir /s /q .next 2>nul
echo.
echo 🚀 Iniciando servidor optimizado...
pnpm dev